"""
syslog 증강 v2 — 카테고리당 70개 추가 (9개 카테고리 × 70 = 630개)
대상: Out_Of_Memory, Memory_Leak, Disk_Full, Process_Crash, DB_Connection,
      Configuration_Error, Port_Conflict, Network_Timeout, Permission_Denied

실행:
    /root/agent/.venv/bin/python3.10 scripts/load_syslog_train_v2.py
    /root/agent/.venv/bin/python3.10 scripts/load_syslog_train_v2.py --remove
"""
import argparse, hashlib, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
import chromadb
from chromadb.config import Settings

CHROMA_DIR      = str(Path(__file__).parent.parent / "data" / "chroma_db")
COLLECTION_NAME = "error_playbook_vectors"
ID_PREFIX       = "syslog_v2_"
SOURCE          = "syslog_augment_v2"

def _md5(s): return hashlib.md5(s.encode()).hexdigest()

# ─────────────────────────────────────────────────────────────────────────────
ENTRIES = []

# ── Out_Of_Memory (70개) ──────────────────────────────────────────────────────
OOM = [
    "kernel: Out of memory: Kill process 1823 (java) score 872 or sacrifice child",
    "kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/tomcat.service,task=java,pid=2041,uid=1001",
    "kernel: Killed process 4512 (python3) total-vm:8192000kB, anon-rss:7340032kB, file-rss:0kB",
    "kernel: Out of memory: Kill process 9021 (node) score 950 or sacrifice child",
    "kernel: oom_reaper: reaped process 3311 (gunicorn), now anon-rss:0kB, file-rss:0kB",
    "kernel: Out of memory: Kill process 7701 (mysqld) score 810 or sacrifice child",
    "kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=/,mems_allowed=0,oom_memcg=/system.slice/mysql.service",
    "kernel: Killed process 6644 (php-fpm) total-vm:4096000kB, anon-rss:3670016kB",
    "java.lang.OutOfMemoryError: Java heap space at com.app.Service.process(Service.java:142)",
    "java.lang.OutOfMemoryError: GC overhead limit exceeded at org.springframework.context.support.AbstractApplicationContext",
    "java.lang.OutOfMemoryError: unable to create new native thread",
    "java.lang.OutOfMemoryError: Metaspace at sun.reflect.GeneratedConstructorAccessor",
    "Exception in thread 'main' java.lang.OutOfMemoryError: Java heap space",
    "fatal error: runtime: out of memory at go/src/runtime/malloc.go",
    "RuntimeError: CUDA out of memory. Tried to allocate 2.50 GiB (GPU 0; 8.00 GiB total capacity)",
    "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB",
    "MemoryError: Unable to allocate 16.0 GiB for an array with shape (2000000000,)",
    "malloc: cannot allocate region of size 8589934592 bytes",
    "mmap failed: Cannot allocate memory (errno=12)",
    "kernel: [1234567.890123] Out of memory: Kill process 2233 (redis-server) score 756",
    "systemd[1]: redis.service: Main process exited, code=killed, status=9/KILL",
    "kernel: oom-kill: Kill process 8877 (celery) score 900, memory_limit 2147483648",
    "python3: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.",
    "Segmentation fault (core dumped) — process ran out of addressable memory",
    "kernel: Out of memory: Kill process 5544 (nginx) score 700 or sacrifice child",
    "Cannot allocate memory in static TLS block — insufficient memory for library load",
    "FATAL: Failed to allocate 4096 MB memory for JVM: Cannot allocate memory",
    "java.lang.OutOfMemoryError: Direct buffer memory",
    "kernel: oom-kill: process python3 pid=9934 score=870 triggered by python3 pid=9934",
    "systemd-oom[812]: Killed process group of service kubelet.service due to memory pressure",
    "docker: Error response from daemon: container killed due to OOM: container used 2.1GB exceeding limit of 2.0GB",
    "cgroup: container memory limit exceeded, killing pid 3310 python3",
    "kernel: Memory cgroup out of memory: Kill process 11002 (uwsgi) score 895",
    "ruby: [BUG] Segmentation fault at 0x00000000000000a8 — heap exhausted",
    "node: /build/node/deps/v8/src/api/api.cc:596: (T*) v8::internal::ToApiHandle<M>(v8::internal::Handle<M>): Assertion failed. — heap limit reached",
    "Go runtime: fatal error: out of memory",
    "PHP Fatal error: Allowed memory size of 536870912 bytes exhausted",
    "R Error: cannot allocate vector of size 8.0 Gb",
    "postgres: out of memory — could not resize shared memory segment",
    "redis: Can't save in background: fork: Cannot allocate memory",
    "elasticsearch: OutOfMemoryError[Java heap space]; nested: ElasticsearchException",
    "kafka: java.lang.OutOfMemoryError: GC overhead limit exceeded in kafka.log.LogSegment",
    "spark: SparkException: Job aborted due to stage failure: OOM in executor",
    "flink: java.lang.OutOfMemoryError: Java heap space at org.apache.flink.runtime.taskmanager",
    "kernel: Out of memory: Kill process 33401 (mongod) score 850 or sacrifice child",
    "mongod: assertionException: 13104 ran out of memory while paging in data",
    "nginx: worker process exited on signal 9 (SIGKILL) — OOM killer terminated",
    "kernel: oom-kill:constraint=CONSTRAINT_CPUSET,task=containerd,pid=4401,uid=0,oom_score_adj=0,mem_cgroup=/",
    "systemd[1]: haproxy.service: Killing process 7723 with signal SIGKILL",
    "kernel: Killed process 19023 (sshd) total-vm:18432kB, anon-rss:7168kB, file-rss:512kB",
    "uwsgi: --- no python application found, check your startup logs for errors --- Killed by OOM",
    "celery: worker: ERROR: OOM kill — worker process 12049 was killed",
    "kernel: oom-kill: task=stress-ng,pid=2233,oom_score=1000,adj=0",
    "airflow: MemoryError during DAG execution — worker memory limit exceeded",
    "kernel: Out of memory: Kill process 45312 (chrome) score 999 or sacrifice child",
    "kernel: oom-kill:constraint=CONSTRAINT_NONE, task=datadog-agent,pid=5513",
    "java: Exception in thread 'GC Thread' java.lang.OutOfMemoryError: Java heap space",
    "jvm: Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded",
    "dotnet: System.OutOfMemoryException: Insufficient memory to continue the execution of the program",
    "rabbitmq: vm_memory_high_watermark reached — connection blocked",
    "containerd: task failed: OOMKilled — container exceeded memory limit",
    "k8s: OOMKilled — container nginx exceeded memory limit of 512Mi",
    "k8s: pod evicted: The node had condition: MemoryPressure",
    "k8s: Evicted pod due to memory pressure — node memory usage above threshold",
    "chronyd: Cannot allocate memory for DNS lookup — system under memory pressure",
    "memcached: failed to allocate slab for 512 bytes — OOM condition",
    "rsyslog: action 'omfwd' suspended, OOM condition detected",
    "postfix: OOM kill signal received — process terminated unexpectedly",
    "sshd: fatal: mm_request_send: write: Broken pipe — OOM caused premature termination",
    "crond: OOM kill detected, some scheduled tasks may have been lost",
]
for t in OOM:
    ENTRIES.append((t, "Out_Of_Memory", "clear_memory", "", ""))

# ── Memory_Leak (70개) ────────────────────────────────────────────────────────
MEMLEAK = [
    "java: Heap memory usage grew from 512MB to 3840MB over 6 hours without GC recovery",
    "java: Old generation heap size increasing: 1GB → 2GB → 3GB → 3.8GB (leak suspected)",
    "node: RSS memory grew from 120MB to 4200MB over 12 hours (pid=4411)",
    "python3: process memory RSS increasing steadily: 256MB → 2048MB — possible leak in object cache",
    "prometheus: memory usage climbing unbounded: 500MB → 2.1GB over 3h — check metric cardinality",
    "grafana: heap_inuse growing 80MB/hour — possible dashboard query leak",
    "ruby: ObjectSpace growing: 1.2M objects at start, 8.7M objects after 4h",
    "go runtime: heap objects grew from 500k to 4.5M — goroutine leak suspected",
    "dotnet: Large Object Heap (LOH) growing steadily — suspected LOH fragmentation leak",
    "redis: used_memory increasing 50MB/hour with stable key count — possible memory fragmentation",
    "postgres: shared_buffers consumption climbing — query result cache not releasing",
    "mysql: innodb_buffer_pool usage at 95% and growing despite low traffic",
    "nginx: worker_processes memory increasing 10MB/hr each — possible connection leak",
    "haproxy: memory usage grew from 256MB to 1.8GB — session table not purging",
    "elasticsearch: field data cache growing unbounded — consider setting indices.fielddata.cache.size",
    "kafka: heap usage climbing in consumer group coordinator — possible leak in offset store",
    "celery: worker RSS growing 30MB per hour — possible circular reference in task chain",
    "gunicorn: worker memory RSS growing: leaked objects detected in gc.get_unreachable()",
    "uwsgi: worker memory growing past safe limit — possible application-level leak",
    "airflow: scheduler heap growing 100MB/hour — check DAG serialization objects",
    "dockerd: memory usage climbing: 800MB → 3.5GB over 24h — layer cache may be leaking",
    "containerd: shim process memory 1.2GB and growing — container cleanup incomplete",
    "k8s: kubelet memory usage growing 20MB/h — possible watch event handler leak",
    "k8s: kube-proxy memory RSS at 2.1GB (expected <200MB) — conntrack table leak",
    "etcd: resident memory 4.1GB and climbing — compaction not effective, possible WAL leak",
    "istio: envoy proxy memory growing 5MB/min — upstream cluster connection leak",
    "vault: memory growing post-seal — possible token store GC delay",
    "consul: agent memory 1.5GB and growing — check catalog gossip buffers",
    "terraform: process memory grew from 200MB to 2.1GB during plan — provider leak",
    "ansible: runner process memory growing linearly with task count",
    "datadog-agent: memory growing 2MB/check cycle — custom check object retention",
    "fluentd: buffer memory growing unbounded — output plugin not draining",
    "logstash: JVM old gen 3.9GB / 4.0GB — persistent queue leak suspected",
    "filebeat: registry memory growing — harvester goroutines not releasing",
    "telegraf: metric buffer growing past flush interval — output plugin stalled",
    "pgbouncer: client_list growing without bound — idle connection not timing out",
    "memcached: slab 42 item count growing — eviction disabled with unlimited memory",
    "varnish: object memory growing: 4GB allocated, 500MB in use but not freed",
    "squid: memory usage at 6.1GB (limit 2GB) — cache_mem not enforced correctly",
    "php-fpm: worker PID 12340 RSS 1.8GB — memory_limit not applying to long-lived workers",
    "rails: Sidekiq job queue growing — possible memory retained between jobs in worker",
    "django: suspected memory leak in middleware — RSS growing with request count",
    "flask: APScheduler job accumulating memory — old job refs not cleared",
    "springboot: actuator /metrics shows heap_used increasing monotonically over 6h",
    "tomcat: Old Gen heap growing after each deployment — class loader leak suspected",
    "jetty: thread-local storage growing per request — possible ThreadLocal leak",
    "wildfly: JVM metaspace growing — classloader leak from hot-redeploy",
    "weblogic: stuck threads consuming memory — transaction timeout not releasing resources",
    "jboss: garbage collection unable to reclaim old generation — heap dump recommended",
    "glassfish: EJB container memory growing — stateful session beans not being passivated",
    "spark: executor JVM heap growing between stages — RDD lineage not being cleared",
    "flink: taskmanager heap growing — checkpoint state backend memory not released",
    "storm: supervisor memory growing — spout ack buffer leak in worker topology",
    "hadoop: namenode heap size 12GB and growing — inode cache not evicting",
    "hbase: regionserver memory growing — block cache not honoring max size",
    "cassandra: heap after GC 7GB (limit 8GB) — off-heap memtable leak",
    "mongodb: wiredtiger cache growing past configured limit — eviction thread stalled",
    "influxdb: series cardinality 12M and growing — tag value explosion causing memory leak",
    "clickhouse: uncompressed_cache growing unbounded — check cache size configuration",
    "druid: historical node memory growing — segment loading cache not evicting",
    "presto: coordinator heap growing — query result cache not expiring old entries",
    "zookeeper: heap at 3.9GB / 4GB — watch event queue accumulating",
    "rabbitmq: queue memory growing — consumer not acknowledging messages",
    "activemq: store usage at 98% — messages accumulating in dead letter queue",
    "nats: slow consumer detected — message buffer growing to 8GB",
    "pulsar: broker memory growing — ledger cache not trimming old entries",
    "chronyd: memory growing due to excessive NTP peer accumulation",
    "systemd: unit tracking memory leak — cgroup accounting overhead growing",
    "rsyslogd: action queue memory growing — remote syslog target unreachable, buffering",
    "journald: journal memory map growing — log rotation not keeping up with ingestion",
    "sshd: memory leak in PAM module — session cleanup incomplete after logout",
]
for t in MEMLEAK:
    ENTRIES.append((t, "Memory_Leak", "clear_memory", "", ""))

# ── Disk_Full (70개) ──────────────────────────────────────────────────────────
DISKFULL = [
    "kernel: EXT4-fs error (device sda1): ext4_find_entry:1455: inode #2: comm mysqld: reading directory lblock 0",
    "kernel: ENOSPC on /dev/sda1 — write failed for process nginx (pid 3311)",
    "cp: error writing '/var/log/app.log': No space left on device",
    "rsync: [receiver] write error: No space left on device (28) at receiver.c(378)",
    "tar: data/backup.tar.gz: Cannot write: No space left on device",
    "dd: error writing '/dev/sdb': No space left on device",
    "postgres: could not write to file 'pg_wal/000000010000001F00000001': No space left on device",
    "mysql: [ERROR] mysqld: Disk is full writing '/var/lib/mysql/binlog.000093' (Errcode: 28 - No space left on device)",
    "mysql: [ERROR] The table '/tmp/mysql.tmp' is full",
    "redis: Background saving error — No space left on device writing /var/lib/redis/dump.rdb",
    "elasticsearch: IOException: failed to write segment file — No space left on device",
    "elasticsearch: DiskThresholdMonitor: high disk watermark [90%] exceeded on [node1]",
    "elasticsearch: DiskThresholdMonitor: flood stage disk watermark [95%] exceeded, index readonly",
    "kafka: IOException: No space left on device — log segment write failed on /var/kafka/data",
    "docker: Error response from daemon: no space left on device",
    "containerd: failed to create snapshot — insufficient disk space",
    "k8s: kubelet disk pressure: imagefs.available < 15%, pod eviction triggered",
    "k8s: DiskPressure condition: node disk usage exceeds eviction threshold",
    "df: /dev/mapper/vg0-lv_root: Use% 100%",
    "logrotate: error: error creating output file /var/log/app/app.log.1: No space left on device",
    "journald: Failed to write entry (28 bytes), ignoring: No space left on device",
    "syslog: kernel: attempt to access beyond end of device sda1 rw=1, want=2097152, limit=1953525168",
    "nginx: [alert] could not open error log file: open() '/var/log/nginx/error.log' failed (28: No space left on device)",
    "apache2: (28)No space left on device: AH00023: Couldn't create the rewrite-map mutex",
    "php-fpm: WARNING: [pool www] child 9821 exited with code 255 — disk full during session write",
    "postfix: fatal: /var/spool/postfix/maildrop/2B4DB3820A6: write error: No space left on device",
    "dovecot: Error: write() failed with errno=28: No space left on device",
    "proftpd: mod_xfer/1.3: error stashing /tmp/pr3Cx3rH4a: No space left on device",
    "vsftpd: 500 OOPS: cannot change directory: No space left on device writing session file",
    "samba: [2024/01/15 03:15:22] write_data: write failure. Error = No space left on device",
    "nfs: nfsd: failing over to read-only — disk full on /export",
    "ceph: OSD.2 full at 95.0%: marking OSD full — writes will be rejected",
    "ceph: cluster is full (>95% capacity) — all writes suspended",
    "glusterfs: write failed: No space left on device on brick /data/brick1",
    "lvm: Insufficient free space: 1 extents needed, but only 0 available",
    "mdadm: [md0] Disk failure on sdb2, disabling device. — array degraded due to full disk",
    "zfs: pool data: Disk is full — transaction failed: ENOSPC",
    "btrfs: BTRFS error (device sdc): enospc, nodesize 16384 free_space 0",
    "tmpfs: write to '/tmp/app_cache/session_12345': No space left on device — tmpfs full",
    "docker: layer write error: No space left on device — overlay2 filesystem exhausted",
    "pip: ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device",
    "npm: ENOSPC: no space left on device, write '/app/node_modules/.cache/...'",
    "gradle: Error: No space left on device during build cache write",
    "maven: Build failure: IOException: No space left on device writing target/classes",
    "git: error: object file /repo/.git/objects/pack/pack-abc123.pack is empty — disk full during push",
    "ansible: fatal: [host1]: FAILED! — {'msg': 'No space left on device writing tmp file'}",
    "jenkins: FATAL: java.io.IOException: No space left on device building workspace",
    "gitlab-runner: ERROR: Uploading artifacts as 'archive' to coordinator... failed: no space left",
    "vault: failed to persist lease: io: write /opt/vault/data: no space left on device",
    "consul: Failed to write snapshot: No space left on device",
    "etcd: failed to write WAL entry: no space left on device",
    "prometheus: failed to write time series data: no space left on device at /var/lib/prometheus",
    "alertmanager: level=error error creating temp file: no space left on device",
    "grafana: level=error t=2024-01-15 msg='failed to write session data' error='no space left on device'",
    "influxdb: engine: error writing data: write /var/lib/influxdb/data/_internal/: no space left on device",
    "mongodb: [WiredTiger] WT_ERROR: No space left on device — failed to open log file",
    "cassandra: java.io.IOException: No space left on device writing sstable /var/cassandra/data",
    "hbase: IOException: No space left on device writing HLog /hbase/WALs",
    "hadoop: namenode: IOException: No space left on device writing edit log segment",
    "spark: java.io.IOException: No space left on device — failed to spill shuffle data",
    "flink: java.io.IOException: No space left on device during checkpoint write",
    "airflow: DagFileProcessorAgent: Failed to persist DAG to disk: No space left on device",
    "celery: ERROR: Failed to create log file: [Errno 28] No space left on device",
    "gunicorn: [CRITICAL] WORKER TIMEOUT (pid:1234) — disk full prevented writing tmp files",
    "uwsgi: write error: No space left on device writing upload buffer to /tmp",
    "fluentd: [error]: failed to write buffer to /var/log/fluentd/buf: No space left on device",
    "logstash: Pipeline error {:pipeline_id=>'main', :exception=>#<Errno::ENOSPC: No space left on device>}",
    "filebeat: Failed to create harvester: Error setting up harvester for file /var/log/app.log: No space left on device",
    "telegraf: Error writing to file /var/lib/telegraf/metrics.db: no space left on device",
    "datadog: Unable to write agent log: No space left on device at /var/log/datadog/agent.log",
    "cron: (root) ERROR (grandchild failed with exit status 1) — No space left on device",
]
for t in DISKFULL:
    ENTRIES.append((t, "Disk_Full", "execute_rule_command", "", "journalctl --vacuum-size 1G"))

# ── Process_Crash (70개) ──────────────────────────────────────────────────────
PCRASH = [
    "kernel: nginx[3421]: segfault at 0 ip 00007f3b1c2a3d40 sp 00007ffd12345678 error 4 in libnginx.so",
    "kernel: python3[9023]: segfault at 7f0000000000 ip 00007f3b44556677 sp 00007ffd88776655 error 6",
    "kernel: mysqld[1234]: segfault at 0 ip 0000000000400000 sp 00007fff12345678 error 14 in mysqld",
    "kernel: redis-server[5511]: segfault at 0 ip 00007f4422334455 sp 00007ffd55443322 error 4",
    "kernel: java[8801]: segfault at 0 ip 00007f123456789a sp 00007ffd98765432 error 6 in libjvm.so",
    "systemd[1]: nginx.service: Main process exited, code=dumped, status=11/SEGV",
    "systemd[1]: mysql.service: Main process exited, code=dumped, status=6/ABRT",
    "systemd[1]: redis.service: Main process exited, code=killed, status=11/SEGV",
    "systemd[1]: postgresql.service: Main process exited, code=dumped, status=11/SEGV",
    "systemd[1]: mongodb.service: Main process exited, code=killed, status=6/ABRT",
    "core dumped — nginx process received SIGSEGV (signal 11) at address 0x00007f1234abcdef",
    "Aborted (core dumped) — python3 received SIGABRT from heap corruption",
    "Fatal Python error: Segmentation fault — memory access violation in C extension",
    "*** Error in 'gunicorn': free(): invalid pointer: 0x00007f1234567890 ***",
    "corrupted double-linked list detected in malloc — process aborted",
    "double free or corruption (!prev) — process terminated with core dump",
    "malloc: error for object 0x7f123456: incorrect checksum for freed object — abort",
    "stack smashing detected: /usr/bin/python3 terminated",
    "*** stack smashing detected ***: terminated",
    "Caught signal 11 (Segmentation fault): backtrace available in /var/crash/app.1234.crash",
    "redis: SIGTERM received, aborting. Bye!",
    "nginx: signal 11 (Segmentation fault) received by worker process — restarting",
    "apache2 child pid 5432 exit signal Segmentation fault (11), possible coredump in /etc/apache2",
    "php-fpm: WARNING: [pool www] child 7891 exited on signal 11 (SIGSEGV)",
    "uwsgi: DAMN ! worker 1 (pid: 4561) died, too many corpses for this worker",
    "gunicorn[2345]: Worker with pid 7890 was terminated due to signal 11",
    "celery: Task received SIGKILL — was forcefully terminated",
    "flower: Process 7891 exited with status 139 (SIGSEGV)",
    "java: A fatal error has been detected by the Java Runtime Environment: SIGSEGV",
    "# A fatal error has been detected by the JVM: SIGBUS (0x7) at pc=0x00007f1234567890",
    "jvm crashed: native memory allocation (mmap) failed to map 2147483648 bytes",
    "postgres: server process (PID 8901) was terminated by signal 11: Segmentation fault",
    "postgres: LOG: server process (PID 7801) was terminated by signal 6: Aborted",
    "postgres: PANIC: pre-existing shared memory block is still in use",
    "mongod: received signal 11 (Segmentation fault), backtrace: [...]",
    "elasticsearch: [ERROR][o.e.b.Bootstrap] node validation exception — process crashed",
    "elasticsearch: A terminally broken JVM was detected — exiting with code 137",
    "kafka: FATAL: Kafka process crashed — JVM terminated with exit code 139",
    "zookeeper: FATAL: process terminated by signal 9 — possible OOM kill",
    "spark executor: ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason: Process exited with code 139",
    "flink: Lost connection to TaskManager — process may have crashed",
    "hadoop: ERROR: Namenode process exited with code 1 — FATAL exception in main thread",
    "rabbitmq: beam.smp crashed with reason: killed",
    "beam.smp: [os_mon] crash report: {process,os_mon} {error_info,killed}",
    "erlang: crash report sent to error_logger — gen_server terminated with reason: normal",
    "dotnet: Application crashed with unhandled exception: System.AccessViolationException",
    "dotnet: Unhandled exception. System.NullReferenceException — process crashed",
    "dotnet: Fatal error. Internal CLR error. (0x80131506)",
    "ruby: [BUG] Segmentation fault at 0x0000000000000008",
    "ruby: Aborted (core dumped) in GC::compact",
    "go: runtime: unexpected return pc for runtime.sigpanic called from ...; fatal error: signal arrived during external code execution",
    "go: SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f1234abcdef",
    "rust: process killed with SIGABRT — thread 'main' panicked at 'attempt to subtract with overflow'",
    "containerd: container exited with code 139 (SIGSEGV): container_id=abc123",
    "docker: container died with exitCode=137: killed by SIGKILL",
    "k8s: container nginx in pod nginx-abc123 terminated: Reason=Error, Exit Code=139",
    "k8s: container app terminated with reason=OOMKilled — combined with SIGSEGV in heap",
    "systemd-coredump[2345]: Process 8901 (nginx) of user 33 dumped core",
    "coredumpctl: /var/lib/systemd/coredump/core.nginx.1234.abcdef12 (signal 11, SIGSEGV)",
    "apport: System detected a program crash: /usr/sbin/nginx crashed with SIGSEGV",
    "watchdog: process nginx (pid=3311) died unexpectedly — restarting",
    "supervisord: exited: app-worker (exit status 139; not expected)",
    "pm2: App [api-server] with id [0] and pid [7890] exited — restarting — status: crashed",
    "forever: [fatal] restart failed — process exiting with non-zero exit code: 139",
    "foreman: SIGCHLD received — worker[1] exited with status 11",
    "runit: service/nginx: runsv nginx: warning: /service/nginx/run exited with status 139",
    "s6: s6-supervise nginx: warning: child 4521 exited with signal 11",
    "monit: nginx (pid 3421) with SIGABRT — process exiting",
    "nagios: SERVICE ALERT: webserver;HTTP;CRITICAL;HARD — process crash detected by check",
    "zabbix: Problem: nginx process not running — crash detected via process monitor",
    "cron: (root) CRASH (crontab command exited with signal 11)",
]
for t in PCRASH:
    ENTRIES.append((t, "Process_Crash", "restart_service", "rsyslog", ""))

# ── DB_Connection (70개) ──────────────────────────────────────────────────────
DBCONN = [
    "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: remaining connection slots are reserved for non-replication superuser connections",
    "psycopg2.OperationalError: FATAL: too many connections for role 'app_user'",
    "FATAL: connection limit exceeded for non-superuser roles — max_connections=100, in use=100",
    "pg: FATAL: max_connections=200 connections are already in use",
    "pgbouncer: pooler error: no more connections allowed (max_client_conn=100)",
    "pgbouncer: S: query_wait_timeout (30) for client: app/127.0.0.1:56789",
    "pgbouncer: FATAL: no more connections allowed — pool is full",
    "mysql: ERROR 1040 (HY000): Too many connections",
    "mysql: [ERROR] Aborted connection 45021 to db: 'app' user: 'webapp' host: '10.0.0.5' (Got a packet bigger than 'max_allowed_packet' bytes)",
    "mysql: connection timeout after 30s — max_connect_errors threshold reached",
    "mysql: [ERROR] Can't create a new thread (errno 11) — too many connections",
    "mysqld: Aborted connection 89012 to db: 'production' host: 'app-server' (Timeout reading communication packets)",
    "redis: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk",
    "redis: ERR max number of clients reached — connection refused",
    "redis: [12345] WARN connected_slaves:0 master_link_status:down — replica connection lost",
    "redis: NOAUTH Authentication required — connection pool using wrong credentials after rotation",
    "mongodb: Error: No primary found in replicaset — connection pool exhausted attempting failover",
    "mongodb: MongoNetworkError: connection 5 to 10.0.0.10:27017 closed",
    "mongodb: MongoTimeoutError: Server selection timed out after 30000ms — no server found matching ReadPreference",
    "mongod: connection pool is exhausted: max_pool_size=100, waiting_queue_timeout exceeded",
    "cassandra: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed",
    "cassandra: PoolingOptions: connection pool for host 10.0.0.5 exhausted (size=128)",
    "cassandra: OperationTimedOutException: Timed out waiting for response from host 10.0.0.5/9042",
    "elasticsearch: NoNodeAvailableException: None of the configured nodes are available",
    "elasticsearch: org.elasticsearch.client.transport.NoNodeAvailableException — connection pool drained",
    "influxdb: ERR: database connection failed — max open connections (100) exceeded",
    "clickhouse: DB::Exception: Max count of simultaneous queries exceeded — Too many connections",
    "timescaledb: connection pool exhausted — could not connect to TimescaleDB after 3 retries",
    "mariadb: ERROR 1040 (HY000): Too many connections — max_connections=500 all in use",
    "oracle: ORA-12520: TNS: listener could not find available handler for requested type of server",
    "oracle: ORA-00018: maximum number of sessions exceeded",
    "mssql: ERROR: Connection pool exhausted. Max pool size was 100",
    "sqlserver: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool",
    "db2: SQL1040N The maximum number of applications is already connected to the database",
    "django.db.utils.OperationalError: could not connect to server: Connection refused",
    "django: DATABASES connection pool exhausted — consider increasing CONN_MAX_AGE",
    "rails: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds",
    "rails: PG::ConnectionBad: SSL connection has been closed unexpectedly — pool exhausted",
    "spring: com.zaxxer.hikari.pool.HikariPool: HikariPool-1 - Connection is not available, request timed out after 30000ms",
    "hikari: pool HikariPool-1 exhausted: maximumPoolSize=10, timeout after 30000ms waiting for connection",
    "c3p0: WARN: Timeout waiting for connection from pool, current connections: 50/50",
    "dbcp: Could not get a resource from the pool: pool exhausted (active=50, idle=0, max=50)",
    "sqlalchemy: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30",
    "peewee: OperationalError: (2003, 'Can't connect to MySQL server on 10.0.0.2 (111)')",
    "typeorm: Error: connect ECONNREFUSED 127.0.0.1:5432 — database connection refused",
    "prisma: Error: Can't reach database server at `localhost:5432` — connection pool exhausted",
    "knex: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full",
    "sequelize: TimeoutError: ResourceRequest timed out — connection pool all busy",
    "gorm: too many open connections: dial tcp 10.0.0.3:3306: connection refused",
    "node-postgres: Error: Client checkout timeout — pool is full after 30s",
    "aiomysql: OperationalError: (1040, 'Too many connections')",
    "asyncpg: asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already",
    "psycopg3: connection pool timeout: max_size=20, queue_timeout=30s exceeded",
    "cx_Oracle: ORA-12170: TNS: Connect Timeout — database unreachable or pool exhausted",
    "pyodbc: Error: ('08001', '[08001] Connection timeout expired — pool exhausted after 30s')",
    "go sql: database/sql: pq: sorry, too many clients already — connection pool exhausted",
    "java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out",
    "java.sql.SQLException: Timeout waiting for connection from pool of size 50",
    "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure — pool exhausted",
    "php: PDOException: SQLSTATE[08006]: Connection failure: 7 FATAL: max connections exceeded",
    "php: mysqli_connect(): (HY000/1040): Too many connections",
    "laravel: SQLSTATE[HY000] [2002] Connection refused — DB_CONNECTION pool not available",
    "symfony: Doctrine\DBAL\Exception\ConnectionException — too many connections to database",
    "flask-sqlalchemy: sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached",
    "celery: kombu.exceptions.OperationalError: [Errno 111] Connection refused — DB broker unavailable",
    "sidekiq: Errno::ECONNREFUSED: Connection refused — Redis connection pool drained",
    "resque: Redis::CannotConnectError: Cannot connect to Redis on 127.0.0.1:6379 — pool empty",
    "delayed_job: ActiveRecord::ConnectionNotEstablished: No connection pool with id primary found",
    "apscheduler: Execution of job failed: psycopg2.OperationalError: connection pool exhausted",
    "alembic: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) too many connections",
]
for t in DBCONN:
    ENTRIES.append((t, "DB_Connection", "execute_rule_command", "", "free -h"))

# ── Configuration_Error (70개) ────────────────────────────────────────────────
CONFERR = [
    "nginx: [emerg] unknown directive 'proxy_cache_invalid' in /etc/nginx/conf.d/app.conf:15",
    "nginx: [emerg] invalid number of arguments in 'worker_processes' directive in /etc/nginx/nginx.conf:4",
    "nginx: [emerg] host not found in upstream 'backend:8080' in /etc/nginx/conf.d/app.conf:22",
    "nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)",
    "apache2: Syntax error on line 15 of /etc/apache2/sites-enabled/app.conf: Invalid command 'SSLCertificateKey'",
    "apache2: AH00526: Premature end of script headers: index.php — misconfigured PHP handler",
    "haproxy: [ALERT] parsing [/etc/haproxy/haproxy.cfg:42] : 'timeout client' expects a positive value in milliseconds",
    "haproxy: [ALERT] parsing [/etc/haproxy/haproxy.cfg:88] : unknown keyword 'ssl-server-verify' in 'defaults' section",
    "mysql: [ERROR] unknown variable 'innodb-buffer-pool-size=invalid' in /etc/mysql/my.cnf",
    "mysql: [ERROR] /etc/mysql/my.cnf: Missing value for key 'bind-address' at line 12",
    "mysql: [ERROR] Conflicting declarations: 'innodb_file_per_table' set twice in configuration",
    "postgres: FATAL: invalid value for parameter 'max_connections': '1000abc'",
    "postgres: FATAL: configuration file '/etc/postgresql/14/main/postgresql.conf' contains errors",
    "postgres: LOG: invalid connection option 'sslcert' — check pg_hba.conf",
    "redis: # Configuration error in /etc/redis/redis.conf: Invalid bind address: '999.999.999.999'",
    "redis: # Invalid requirepass option: password too short (minimum 8 characters required)",
    "redis: # Bad directive or wrong number of arguments in /etc/redis/redis.conf at line 45",
    "redis: # Failed to configure server: invalid port number for 'cluster-announce-port'",
    "mongodb: error: mongod failed to start: BadValue: Invalid value for setParameter 'wiredTigerEngineRuntimeConfig'",
    "mongod: Error parsing INI config file: unrecognised option 'storage.mmapv1.journal.enabled'",
    "elasticsearch: failed to load settings from configuration file — invalid YAML at line 23",
    "elasticsearch: ElasticsearchException: illegal value for [cluster.initial_master_nodes] — empty list",
    "kafka: FATAL: error configuring log4j properties — log4j.properties parse error",
    "kafka: Configuration invalid: listeners=PLAINTEXT://:9092,SSL://:9093 — SSL keystore not configured",
    "zookeeper: FATAL: Invalid configuration: dataDir path '/var/zookeeper' does not exist",
    "rabbitmq: failed to start rabbit: {error, {could_not_start, rabbit, {bad_return_value, {error, {missing_required_env_var, RABBITMQ_ERLANG_COOKIE}}}}}",
    "celery: ImproperlyConfigured: result_backend must be set when CELERY_TASK_ALWAYS_EAGER=False",
    "django: ImproperlyConfigured: Requested setting DATABASES, but settings are not configured",
    "django: django.core.exceptions.ImproperlyConfigured: 'django.contrib.auth' requires 'django.contrib.contenttypes'",
    "flask: RuntimeError: A secret key is required to use CSRF — set SECRET_KEY in configuration",
    "fastapi: pydantic.error_wrappers.ValidationError: value is not a valid integer for field DATABASE_POOL_SIZE",
    "spring: Failed to bind properties under 'spring.datasource.url' to java.lang.String — property missing",
    "spring: APPLICATION FAILED TO START — Description: Failed to configure a DataSource: 'url' attribute is not specified",
    "spring: java.lang.IllegalArgumentException: Could not resolve placeholder 'app.api.key' in value '${app.api.key}'",
    "rails: Rails.configuration: Missing required configuration key 'secret_key_base'",
    "rails: Bundler::GemfileError: Your Gemfile has no gem — syntax error on line 15",
    "node: Error: Cannot find module 'config' — check NODE_ENV and config directory",
    "node: SyntaxError: Unexpected token in JSON at position 0 — config.json is malformed",
    "dotenv: MissingEnvVarsError: Missing required environment variables: DATABASE_URL, REDIS_URL",
    "pydantic: ValidationError: 4 validation errors for Settings — invalid configuration values",
    "ansible: ERROR! Syntax Error while loading YAML. mapping values are not allowed here at line 23",
    "ansible: ERROR! the role 'common' was not found in /etc/ansible/roles — check roles_path",
    "terraform: Error: Invalid expression — expected closing brace, got EOF at main.tf:45",
    "terraform: Error: Unsupported argument — An argument named 'unsupported_option' is not expected here",
    "helm: Error: values.yaml: parsing error: yaml: line 23: did not find expected key",
    "helm: Error: render error in 'mychart/templates/deployment.yaml': template: invalid syntax",
    "k8s: error: error validating 'deployment.yaml': error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field 'limits_invalid'",
    "k8s: cannot unmarshal number into Go struct field Container.spec.containers.resources.limits.cpu of type resource.Quantity",
    "docker: invalid reference format — check image name in docker-compose.yml",
    "docker-compose: yaml.ScannerError: mapping values are not allowed here at line 15",
    "systemd: nginx.service: Unit configuration error — ExecStart missing in [Service] section",
    "systemd: Failed to load configuration for nginx.service: Invalid argument",
    "supervisor: Error: could not read config file /etc/supervisord.conf: No such file or directory",
    "supervisor: Error: program 'app' has no 'command' option — required configuration missing",
    "logrotate: error: error in log rotation script: unknown option 'compress_ext'",
    "crontab: errors in crontab file, can't install — invalid time specification on line 5",
    "sshd: /etc/ssh/sshd_config: line 45: Bad configuration option: 'permitRootLogin invalid'",
    "sshd: error: Bind to port 22 on 0.0.0.0 failed: Permission denied — check sshd_config Port",
    "fail2ban: ERROR: Failed during configuration: 'jail.conf' is unparseable: No section: 'sshd'",
    "postfix: fatal: /etc/postfix/main.cf, line 45: missing '=' after attribute name",
    "postfix: fatal: inet_interfaces: could not find any active network interfaces — check main.cf",
    "exim: Configuration error: unknown option 'dkim_domain' — check exim4.conf",
    "rsyslog: config error: invalid directive '$InputTCPServerPort invalid_port' in /etc/rsyslog.conf",
    "filebeat: Exiting: error loading config file: yaml: line 12: mapping values are not allowed",
    "logstash: Pipeline aborted due to error — configuration error in filter grok pattern",
    "fluentd: [error]: config error file='/etc/fluentd/fluent.conf' error_class=Fluent::ConfigError",
    "telegraf: E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf: invalid TOML",
    "prometheus: error loading config file: yaml: unmarshal errors — invalid scrape_interval",
    "alertmanager: level=error error='error loading config from /etc/alertmanager/alertmanager.yml': yaml: did not find expected key",
    "grafana: level=crit error=Failed to parse '/etc/grafana/grafana.ini': Key mapping error",
]
for t in CONFERR:
    ENTRIES.append((t, "Configuration_Error", "escalate_to_human", "", ""))

# ── Port_Conflict (70개) ──────────────────────────────────────────────────────
PORTCONF = [
    "nginx: bind() to 0.0.0.0:80 failed (98: Address already in use)",
    "nginx: bind() to 0.0.0.0:443 failed (98: Address already in use)",
    "apache2: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80",
    "apache2: no listening sockets available, shutting down — port 80 in use",
    "tomcat: LifecycleException: A child component failed during start — port 8080 in use",
    "tomcat: java.net.BindException: Address already in use — port 8080 is occupied",
    "jetty: java.net.BindException: Address already in use — Failed to bind to port 8443",
    "gunicorn: socket.error: [Errno 98] Address already in use — port 8000",
    "uwsgi: bind(): Address already in use on port 9000 — another uwsgi process running?",
    "flask: OSError: [Errno 98] Address already in use — port 5000 is occupied",
    "fastapi: ERROR: [Errno 98] Address already in use — port 8001 already bound",
    "node: Error: listen EADDRINUSE: address already in use :::3000",
    "node: Error: listen EADDRINUSE: address already in use 0.0.0.0:4000",
    "express: Error: listen EADDRINUSE: address already in use :::8080",
    "django: Error: That port 8000 is already in use.",
    "rails: Address already in use - bind(2) for '127.0.0.1' port 3000",
    "spring: Web server failed to start. Port 8080 was already in use.",
    "spring: Caused by: java.net.BindException: Address already in use — port 8443 conflict",
    "dotnet: Failed to bind to address https://0.0.0.0:5001 — address already in use",
    "dotnet: Unhandled exception: System.Net.Sockets.SocketException: address already in use",
    "go net: listen tcp :9090 bind: address already in use",
    "rust: thread 'main' panicked at 'Os { code: 98, kind: AddrInUse, message: Address already in use }'",
    "java: java.net.BindException: Address already in use — port 7077 (Spark master conflict)",
    "python: OSError: [Errno 98] Address already in use — flask dev server conflict on port 5000",
    "ruby: Errno::EADDRINUSE: Address already in use - bind(2) for '0.0.0.0' port 3000",
    "php: PHP Warning: socket_bind(): unable to bind address [0.0.0.0] port [9000]: Address already in use",
    "postgres: FATAL: could not bind IPv4 address '127.0.0.1': Address already in use",
    "postgres: FATAL: pre-existing shared memory block is still in use — stale postmaster.pid",
    "mysql: [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use",
    "mysql: [ERROR] Do you already have another mysqld server running on port 3306?",
    "redis: Creating Server TCP listening socket 127.0.0.1:6379: bind: Address already in use",
    "mongodb: Cannot assign requested address for socket on port 27017 — port conflict",
    "mongod: Failed to set up listener: SocketException: Address already in use — port 27017",
    "elasticsearch: BindTransportException: Failed to bind to [9300] — port conflict",
    "elasticsearch: failed to bind service on {0.0.0.0:9200} — address already in use",
    "kafka: ERROR Unable to bind to port 9092 — another Kafka broker already listening",
    "zookeeper: ERROR Unable to bind to port 2181 — port already in use by another ZK instance",
    "rabbitmq: BOOT FAILED: {could_not_start, rabbit, {error, {cannot_listen, {'0.0.0.0', 5672, eaddrinuse}}}}",
    "nats: nats-server: listen tcp 0.0.0.0:4222: bind: address already in use",
    "etcd: failed to listen on address http://0.0.0.0:2380 — port already in use",
    "consul: [ERR] agent: error starting agent: error starting rpc listener: listen tcp 0.0.0.0:8300: bind: address already in use",
    "vault: Error initializing listener: listen tcp 0.0.0.0:8200: bind: address already in use",
    "prometheus: listen tcp 0.0.0.0:9090: bind: address already in use",
    "alertmanager: listen tcp 0.0.0.0:9093: bind: address already in use",
    "grafana: Failed to listen on addr=0.0.0.0, port=3000, network=tcp: bind: address already in use",
    "kibana: Port 5601 is already in use",
    "jupyter: ERROR: the notebook server could not be started because no available port could be found — trying next port after 8888",
    "streamlit: Port 8501 is already in use — start another streamlit instance on a different port",
    "airflow: Address already in use — Airflow webserver port 8080 conflict",
    "mlflow: Error: [Errno 98] Address already in use — port 5000 for tracking server",
    "grpc: failed to listen on port 50051: bind: address already in use",
    "thrift: address already in use: port 9090 for thrift RPC server",
    "haproxy: [ALERT] cannot bind socket [0.0.0.0:80] — address already in use",
    "traefik: listen tcp :80 bind: address already in use",
    "envoy: exiting — Port 15001 already in use (istio sidecar conflict)",
    "linkerd: error starting proxy: listen tcp :4143: bind: address already in use",
    "docker: Bind for 0.0.0.0:8080 failed: port is already allocated",
    "docker-compose: ERROR: for service app Cannot start: port is already allocated — 0.0.0.0:8080",
    "k8s: Failed to create pod sandbox: error creating container: failed to bind port 80 — host port conflict",
    "k8s: hostPort conflict: port 8080 already in use by another pod on this node",
    "k8s: nodePort 30000 is already allocated to service other-svc",
    "kernel: netstat: Address already in use — ESTABLISHED connection on 0.0.0.0:9092",
    "ss: LISTEN: 0.0.0.0:6379 — port 6379 already in use (redis not stopped before restart)",
    "fuser: 8080/tcp: 3421 3422 3423 — multiple processes bound to port 8080",
    "lsof: COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME: nginx 3421 root 8u IPv4 — port conflict",
    "netstat: tcp LISTEN 0 128 0.0.0.0:443 0.0.0.0:* — port 443 already occupied",
    "supervisord: ERROR: failed to start nginx — port 80 in use by pid 5421",
    "pm2: Error: listen EADDRINUSE: address already in use :::3000",
    "systemd: nginx.service start operation timed out — port 80 not released by previous instance",
    "chronyd: Can't bind the NTP socket — port 123 already in use",
    "ntpd: Cannot bind socket on port 123 — address already in use",
]
for t in PORTCONF:
    ENTRIES.append((t, "Port_Conflict", "execute_rule_command", "", "ss -tuln"))

# ── Network_Timeout (70개) ────────────────────────────────────────────────────
NETTIMEOUT = [
    "curl: (28) Operation timed out after 30000 milliseconds with 0 bytes received",
    "curl: (7) Failed to connect to api.example.com port 443 after 30011 ms: Timed out",
    "wget: error: timed out reading response — upstream connection timeout after 60s",
    "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError)",
    "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='backend', port=8080): Read timed out. (read timeout=30)",
    "urllib.error.URLError: <urlopen error timed out>",
    "aiohttp.ServerTimeoutError: Timeout on reading data from socket — upstream timeout",
    "httpx.ConnectTimeout: timed out while connecting to host 'database.internal' on port 5432",
    "grpc: StatusCode.DEADLINE_EXCEEDED — RPC deadline exceeded after 30s",
    "grpc: context deadline exceeded — connection to 10.0.0.5:50051 timed out",
    "io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 30.000000000s",
    "thrift.transport.TTransport.TTransportException: TSocket read 0 bytes — connection timeout",
    "java.net.SocketTimeoutException: Read timed out after 30000ms",
    "java.net.SocketTimeoutException: connect timed out — unable to reach 10.0.0.3:8080",
    "java.net.ConnectException: Connection timed out: connect to 10.0.0.5/port 3306",
    "java.io.IOException: Remote end closed connection unexpectedly — network timeout",
    "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure — last packet sent 30010ms ago",
    "com.rabbitmq.client.AlreadyClosedException: channel is already closed due to connection timeout",
    "org.apache.http.conn.ConnectTimeoutException: Connect to backend:8080 timed out",
    "org.springframework.web.client.ResourceAccessException: I/O error on GET request: Read timed out",
    "axios error: timeout of 30000ms exceeded — ECONNABORTED at createError",
    "fetch: AbortError: The operation was aborted — fetch timeout after 30s",
    "node: Error: connect ETIMEDOUT 10.0.0.5:5432 — database connection timeout",
    "node: Error: read ECONNRESET — connection forcibly closed by upstream server",
    "go: dial tcp 10.0.0.3:6379: i/o timeout — context deadline exceeded",
    "go: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
    "go: context deadline exceeded (Client.Timeout exceeded while reading body)",
    "python: socket.timeout: timed out connecting to 10.0.0.5:5432",
    "python: TimeoutError: [Errno 110] Connection timed out to 10.0.0.4:6379",
    "ruby: Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:0x00007f1234567890>",
    "ruby: Errno::ETIMEDOUT: Connection timed out - connect(2) for '10.0.0.2' port 3306",
    "php: Warning: fsockopen(): unable to connect to 10.0.0.5:6379 (Connection timed out)",
    "php: PDOException: SQLSTATE[HY000] [2002] Connection timed out",
    "nginx: upstream timed out (110: Connection timed out) while reading response header from upstream",
    "nginx: upstream timed out (110: Connection timed out) while connecting to upstream",
    "haproxy: backend backend_servers has no server available — all timed out",
    "haproxy: server backend/web1 is DOWN — health check timeout exceeded",
    "traefik: [ERROR] dial tcp 10.0.0.3:8080: i/o timeout — backend unreachable",
    "envoy: upstream_reset_before_response_started{connection_timeout} — request timed out",
    "istio: upstream request timeout — 504 Gateway Timeout after 30s",
    "aws: RequestTimeout: HTTP 408 Request Timeout contacting endpoint 'https://s3.amazonaws.com'",
    "aws sdk: context deadline exceeded when calling SQS.ReceiveMessage — network latency",
    "gcp: DeadlineExceeded: Deadline exceeded at google.cloud.pubsub.v1.Subscriber.Pull",
    "azure: RequestTimeoutException: The request timed out waiting for a response from storage.azure.com",
    "k8s: Error: context deadline exceeded — kubectl apply timed out waiting for API server",
    "k8s: Probe failed: Get 'http://10.244.0.5:8080/healthz': context deadline exceeded (Client.Timeout exceeded)",
    "k8s: Readiness probe failed: HTTP probe failed with statuscode: 504 — upstream timeout",
    "k8s: Service mesh timeout: upstream request timeout exceeded 30s for pod app-abc123",
    "docker: Error response from daemon: context deadline exceeded — pull timed out",
    "celery: SOFT_TIME_LIMIT exceeded — task timed out after 600s retrying",
    "celery: Task timed out: billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(3600)",
    "sidekiq: Timeout::Error: Timeout occurred after 30s waiting for Redis response",
    "resque: Errno::ETIMEDOUT: Connection timed out to Redis host",
    "temporal: TimeoutError: ScheduleToStart timeout exceeded for activity task",
    "airflow: Task exited with return code -9 due to execution_timeout exceeded",
    "spark: Connection to 10.0.0.5:7077 timed out — Spark master unreachable",
    "kafka: TimeoutException: Timeout of 30000ms expired before the position for partition could be determined",
    "kafka: NetworkException: Disconnected from node 2 — broker connection timeout",
    "elasticsearch: ReceiveTimeoutTransportException: [node1] request_id [12345] timed out",
    "mongodb: MongoSocketReadTimeoutException: Timeout while receiving message after 30000ms",
    "redis: ERROR: Connection timed out after 30s — SLAVEOF connection to master dropped",
    "nats: nats: timeout waiting for server response — connection to 10.0.0.5:4222 timed out",
    "etcd: context deadline exceeded — follower failed to get response from leader in time",
    "consul: rpc error: code = DeadlineExceeded — health check timed out after 30s",
    "vault: context deadline exceeded — failed to renew token before expiry",
    "prometheus: context deadline exceeded — scrape target 10.0.0.5:9090 timed out after 10s",
    "alertmanager: Post 'http://slack.webhook.url': context deadline exceeded",
    "postgres: could not send data to client: context deadline exceeded — client timeout",
    "mysql: ERROR 2013 (HY000): Lost connection to MySQL server during query — network timeout",
    "ssh: connect to host 10.0.0.5 port 22: Connection timed out",
]
for t in NETTIMEOUT:
    ENTRIES.append((t, "Network_Timeout", "execute_rule_command", "", "ss -tuln"))

# ── Permission_Denied (70개) ──────────────────────────────────────────────────
PERMDENY = [
    "nginx: open() '/var/www/html/index.php' failed (13: Permission denied)",
    "nginx: [crit] 3421#3421: *1 open() '/etc/ssl/private/nginx.key' failed (13: Permission denied)",
    "apache2: (13)Permission denied: AH00035: access to /var/www/app denied because search permissions are missing",
    "apache2: (13)Permission denied: file permissions deny server access: /var/www/html/config.php",
    "php-fpm: WARNING: [pool www] child 4321 cannot open access to /var/www/app/storage/logs: permission denied",
    "gunicorn: PermissionError: [Errno 13] Permission denied: '/var/log/gunicorn/access.log'",
    "uwsgi: open(): Permission denied [core/uwsgi.c line 1320] — cannot write pid file",
    "django: PermissionError: [Errno 13] Permission denied: '/var/www/app/media/uploads/file.jpg'",
    "flask: PermissionError: [Errno 13] Permission denied: '/etc/ssl/certs/app.crt'",
    "rails: Errno::EACCES (Permission denied @ dir_s_mkdir - /var/www/app/tmp/cache)",
    "node: Error: EACCES: permission denied, open '/etc/nginx/sites-enabled/app.conf'",
    "node: Error: EACCES: permission denied, mkdir '/var/log/node-app'",
    "python: PermissionError: [Errno 13] Permission denied: '/etc/cron.d/backup'",
    "python: IOError: [Errno 13] Permission denied: '/var/run/app.pid'",
    "go: open /etc/ssl/private/ca.key: permission denied",
    "go: mkdir /var/log/app: permission denied",
    "rust: Error: Permission denied (os error 13) opening /etc/shadow",
    "java: java.io.FileNotFoundException: /var/log/app/app.log (Permission denied)",
    "java: java.io.IOException: Permission denied opening /etc/hosts",
    "dotnet: UnauthorizedAccessException: Access to the path '/etc/ssl/certs/server.crt' is denied",
    "mysql: ERROR 13 (HY000): Can't get stat of '/var/lib/mysql/data' (Errcode: 13 - Permission denied)",
    "mysql: [ERROR] Can't create/write to file '/tmp/mysql_tmpfile' (Errcode: 13 - Permission denied)",
    "postgres: could not open file '/var/lib/postgresql/14/main/pg_hba.conf': Permission denied",
    "postgres: FATAL: could not open file '/etc/ssl/certs/server.crt': Permission denied",
    "redis: Permission denied creating /var/run/redis/redis-server.pid",
    "redis: Can't open /var/log/redis/redis-server.log: Permission denied",
    "mongodb: Failed to unlink socket file: /tmp/mongodb-27017.sock, reason: Permission denied",
    "mongod: Insufficient permissions to access directory '/var/lib/mongodb'",
    "elasticsearch: AccessDeniedException /var/lib/elasticsearch/nodes",
    "elasticsearch: Failed to create path for data storage — permission denied on /var/lib/elasticsearch",
    "kafka: java.io.IOException: No such file or directory — Permission denied writing log segment",
    "zookeeper: IOException: Permission denied creating /var/lib/zookeeper/myid",
    "docker: permission denied while trying to connect to the Docker daemon socket — /var/run/docker.sock",
    "docker: Got permission denied accessing /var/run/docker.sock — add user to docker group",
    "docker: failed to create endpoint: Error response: mkdir /var/lib/docker/volumes: permission denied",
    "containerd: failed to load snapshot store: open /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs: permission denied",
    "k8s: pods 'nginx-abc123' is forbidden: User 'system:serviceaccount:default:default' cannot get resource 'pods'",
    "k8s: Error from server (Forbidden): pods is forbidden — RBAC authorization denied",
    "k8s: exec /docker-entrypoint.sh: permission denied — container entrypoint not executable",
    "helm: Error: UPGRADE FAILED: configmaps is forbidden: User 'system:serviceaccount:default:tiller'",
    "ansible: fatal: FAILED: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)",
    "ansible: FAILED: file /etc/nginx/nginx.conf: chown failed — Operation not permitted",
    "ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)",
    "ssh: Warning: Permanently added '10.0.0.5' (ECDSA) to the list of known hosts — Permission denied (publickey)",
    "rsync: rsync: [sender] send_files failed to open '/etc/shadow': Permission denied (13)",
    "scp: /var/backups/db.sql: Permission denied",
    "git: error: open('/var/www/repo/.git/COMMIT_EDITMSG'): Permission denied",
    "git: error: insufficient permission for adding an object to repository database .git/objects",
    "pip: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages'",
    "npm: Error: EACCES: permission denied, mkdir '/home/user/.npm'",
    "npm: npm warn logfile could not be opened: /var/log/npm.log permission denied",
    "systemctl: Failed to enable unit: Permission denied",
    "systemctl: Failed to restart nginx.service: Permission denied",
    "crontab: must be privileged to use -u — Permission denied",
    "cron: (CRON) Permission denied: cannot write /var/spool/cron/crontabs/app",
    "logrotate: error: error creating output file /var/log/app/app.log.1: Permission denied",
    "journalctl: Failed to write: Permission denied to /var/log/journal/",
    "rsyslogd: Error: Permission denied writing to /var/log/secure",
    "filebeat: open /var/log/nginx/access.log: permission denied",
    "fluentd: [error]: unexpected error error_class=Errno::EACCES error='Permission denied @ rb_sysopen - /var/log/app/app.log'",
    "logstash: Permission denied writing to /var/log/logstash/logstash-plain.log",
    "telegraf: E! Permission denied opening /proc/net/dev — check telegraf user permissions",
    "prometheus: level=error file=prometheus.go open /var/lib/prometheus/data: permission denied",
    "grafana: level=error Failed to write to file: permission denied /var/lib/grafana/grafana.db",
    "vault: Error initializing storage of type file: open /opt/vault/data: permission denied",
    "consul: Failed to load state: open /var/consul/serf/local.snapshot: permission denied",
    "etcd: open /var/lib/etcd/member/snap/db: permission denied",
    "certbot: Permission denied trying to create /etc/letsencrypt/live",
    "openssl: Permission denied — cannot write certificate to /etc/ssl/certs/server.crt",
    "chmod: changing permissions of '/etc/sudoers': Operation not permitted",
    "chown: changing ownership of '/var/lib/app': Operation not permitted (requires root)",
    "mount: /dev/sdb1: can't read superblock — permission denied",
    "iptables: Permission denied (you must be root) — firewall rule change failed",
]
for t in PERMDENY:
    ENTRIES.append((t, "Permission_Denied", "escalate_to_human", "", ""))

# ─────────────────────────────────────────────────────────────────────────────

def main(remove: bool = False):
    client = chromadb.PersistentClient(
        path=CHROMA_DIR,
        settings=Settings(anonymized_telemetry=False),
    )
    col = client.get_collection(COLLECTION_NAME)
    before = col.count()

    if remove:
        data = col.get(include=["metadatas"])
        rm = [data["ids"][i] for i, m in enumerate(data["metadatas"])
              if m.get("source") == SOURCE]
        if rm:
            col.delete(ids=rm)
        print(f"삭제 완료: {len(rm)}개 | 현재 {col.count()}개")
        return

    # 중복 제거 후 적재
    seen: set[str] = set()
    ids, docs, metas = [], [], []
    for text, cat, action, target, command in ENTRIES:
        uid = ID_PREFIX + _md5(text)
        if uid in seen:
            continue
        seen.add(uid)
        ids.append(uid)
        docs.append(text)
        metas.append({
            "error_category": cat,
            "action_type":    action,
            "target_process": target,
            "command":        command,
            "source":         SOURCE,
        })

    batch = 100
    upserted = 0
    for i in range(0, len(ids), batch):
        col.upsert(ids=ids[i:i+batch], documents=docs[i:i+batch], metadatas=metas[i:i+batch])
        upserted += len(ids[i:i+batch])

    after = col.count()
    print(f"완료: {upserted}개 upsert | ChromaDB {before} → {after}개")

    # 카테고리별 집계
    from collections import Counter
    cat_counts = Counter(m["error_category"] for m in metas)
    for cat, cnt in sorted(cat_counts.items()):
        print(f"  {cat:<25} {cnt:>4}개")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--remove", action="store_true")
    args = parser.parse_args()
    main(remove=args.remove)
